package com.example.onemarket.presentation.login

data class Country(
    val name: String,
    val code: String,
    val flag: String,

    val phoneLength: Int,

    val phoneHint: String
)

object CountryData {
    val countries = listOf(
        Country("Azərbaycan",    "+994", "🇦🇿",  9,  "XX XXX XX XX"),
        Country("Türkiyə",       "+90",  "🇹🇷", 10,  "XXX XXX XX XX"),
        Country("Rusiya",        "+7",   "🇷🇺", 10,  "XXX XXX XX XX"),
        Country("Amerika",       "+1",   "🇺🇸", 10,  "XXX XXX XXXX"),
        Country("Böyük Britaniya", "+44","🇬🇧", 10,  "XXXX XXX XXX"),
        Country("Almaniya",      "+49",  "🇩🇪", 10,  "XXX XXXXXXX"),
        Country("Fransa",        "+33",  "🇫🇷",  9,  "X XX XX XX XX"),
        Country("İtaliya",       "+39",  "🇮🇹", 10,  "XXX XXX XXXX"),
        Country("İspaniya",      "+34",  "🇪🇸",  9,  "XXX XXX XXX"),
        Country("Niderland",     "+31",  "🇳🇱",  9,  "X XX XX XXXX"),
        Country("Ukrayna",       "+380", "🇺🇦",  9,  "XX XXX XXXX"),
        Country("Gürcüstan",     "+995", "🇬🇪",  9,  "XXX XXX XXX"),
        Country("Ermənistan",    "+374", "🇦🇲",  8,  "XX XX XX XX"),
        Country("Qazaxıstan",    "+7",   "🇰🇿", 10,  "XXX XXX XX XX"),
        Country("Özbəkistan",    "+998", "🇺🇿",  9,  "XX XXX XX XX"),
        Country("Türkmənistan",  "+993", "🇹🇲",  8,  "XXXX XXXX"),
        Country("Tacikistan",    "+992", "🇹🇯",  9,  "XX XXX XXXX"),
        Country("Qırğızıstan",   "+996", "🇰🇬",  9,  "XXX XXX XXX"),
        Country("Belarus",       "+375", "🇧🇾",  9,  "XX XXX XX XX"),
        Country("Polşa",         "+48",  "🇵🇱",  9,  "XXX XXX XXX"),
        Country("Çexiya",        "+420", "🇨🇿",  9,  "XXX XXX XXX"),
        Country("Avstriya",      "+43",  "🇦🇹",  9,  "XXX XXXXXX"),
        Country("İsveçrə",       "+41",  "🇨🇭",  9,  "XX XXX XX XX"),
        Country("Belçika",       "+32",  "🇧🇪",  9,  "XXX XX XX XX"),
        Country("İsveç",         "+46",  "🇸🇪",  9,  "XXX XXX XXX"),
        Country("Norveç",        "+47",  "🇳🇴",  8,  "XXXX XXXX"),
        Country("Finlandiya",    "+358", "🇫🇮",  9,  "XX XXX XXXX"),
        Country("Danimarka",     "+45",  "🇩🇰",  8,  "XXXX XXXX"),
        Country("Portuqaliya",   "+351", "🇵🇹",  9,  "XXX XXX XXX"),
        Country("Yunanıstan",    "+30",  "🇬🇷", 10,  "XXX XXX XXXX"),
        Country("Rumıniya",      "+40",  "🇷🇴",  9,  "XXX XXX XXX"),
        Country("Bolqarıstan",   "+359", "🇧🇬",  9,  "XXX XXX XXX"),
        Country("Macarıstan",    "+36",  "🇭🇺",  9,  "XX XXX XXXX"),
        Country("Slovakiya",     "+421", "🇸🇰",  9,  "XXX XXX XXX"),
        Country("Xorvatiya",     "+385", "🇭🇷",  9,  "XX XXX XXXX"),
        Country("Serbiya",       "+381", "🇷🇸",  8,  "XX XXX XXX"),
        Country("İsrail",        "+972", "🇮🇱",  9,  "XX XXX XXXX"),
        Country("Ərəbistan",     "+966", "🇸🇦",  9,  "XX XXX XXXX"),
        Country("BƏƏ",           "+971", "🇦🇪",  9,  "XX XXX XXXX"),
        Country("Qatar",         "+974", "🇶🇦",  8,  "XXXX XXXX"),
        Country("Küveyt",        "+965", "🇰🇼",  8,  "XXXX XXXX"),
        Country("İran",          "+98",  "🇮🇷", 10,  "XXX XXX XXXX"),
        Country("İraq",          "+964", "🇮🇶", 10,  "XXX XXX XXXX"),
        Country("Çin",           "+86",  "🇨🇳", 11,  "XXX XXXX XXXX"),
        Country("Yaponiya",      "+81",  "🇯🇵", 10,  "XX XXXX XXXX"),
        Country("Koreya",        "+82",  "🇰🇷", 10,  "XXX XXXX XXXX"),
        Country("Hindistan",     "+91",  "🇮🇳", 10,  "XXXXX XXXXX"),
        Country("Pakistan",      "+92",  "🇵🇰", 10,  "XXX XXXXXXX"),
        Country("Braziliya",     "+55",  "🇧🇷", 11,  "XX XXXXX XXXX"),
        Country("Argentina",     "+54",  "🇦🇷", 10,  "XXX XXX XXXX"),
        Country("Meksika",       "+52",  "🇲🇽", 10,  "XXX XXX XXXX"),
        Country("Kanada",        "+1",   "🇨🇦", 10,  "XXX XXX XXXX"),
        Country("Avstraliya",    "+61",  "🇦🇺",  9,  "XXX XXX XXX"),
        Country("Yeni Zelandiya","+64",  "🇳🇿",  9,  "XXX XXX XXX"),
        Country("Cənubi Afrika", "+27",  "🇿🇦",  9,  "XX XXX XXXX"),
        Country("Nigeriya",      "+234", "🇳🇬", 10,  "XXX XXX XXXX"),
        Country("Misir",         "+20",  "🇪🇬", 10,  "XXX XXX XXXX"),
        Country("Mərakeş",       "+212", "🇲🇦",  9,  "XXX XXX XXX"),
        Country("Tailand",       "+66",  "🇹🇭",  9,  "XX XXX XXXX"),
        Country("Vyetnam",       "+84",  "🇻🇳",  9,  "XXX XXX XXX"),
        Country("Malayziya",     "+60",  "🇲🇾",  9,  "XX XXX XXXX"),
        Country("Sinqapur",      "+65",  "🇸🇬",  8,  "XXXX XXXX"),
        Country("İndoneziya",    "+62",  "🇮🇩", 10,  "XXX XXX XXXX"),
        Country("Filippin",      "+63",  "🇵🇭", 10,  "XXX XXX XXXX")
    )
}