package com.example.onemarket.presentation.login

data class Country(
    val name: String,
    val code: String,
    val flag: String
)

object CountryData {
    val countries = listOf(
        Country("Azərbaycan", "+994", "🇦🇿"),
        Country("Türkiyə", "+90", "🇹🇷"),
        Country("Rusiya", "+7", "🇷🇺"),
        Country("Amerika", "+1", "🇺🇸"),
        Country("Böyük Britaniya", "+44", "🇬🇧"),
        Country("Almaniya", "+49", "🇩🇪"),
        Country("Fransa", "+33", "🇫🇷"),
        Country("İtaliya", "+39", "🇮🇹"),
        Country("İspaniya", "+34", "🇪🇸"),
        Country("Niderland", "+31", "🇳🇱"),
        Country("Ukrayna", "+380", "🇺🇦"),
        Country("Gürcüstan", "+995", "🇬🇪"),
        Country("Ermənistan", "+374", "🇦🇲"),
        Country("Qazaxıstan", "+7", "🇰🇿"),
        Country("Özbəkistan", "+998", "🇺🇿"),
        Country("Türkmənistan", "+993", "🇹🇲"),
        Country("Tacikistan", "+992", "🇹🇯"),
        Country("Qırğızıstan", "+996", "🇰🇬"),
        Country("Belarus", "+375", "🇧🇾"),
        Country("Polşa", "+48", "🇵🇱"),
        Country("Çexiya", "+420", "🇨🇿"),
        Country("Avstriya", "+43", "🇦🇹"),
        Country("İsveçrə", "+41", "🇨🇭"),
        Country("Belçika", "+32", "🇧🇪"),
        Country("İsveç", "+46", "🇸🇪"),
        Country("Norveç", "+47", "🇳🇴"),
        Country("Finlandiya", "+358", "🇫🇮"),
        Country("Danimarka", "+45", "🇩🇰"),
        Country("Portuqaliya", "+351", "🇵🇹"),
        Country("Yunanıstan", "+30", "🇬🇷"),
        Country("Rumıniya", "+40", "🇷🇴"),
        Country("Bolqarıstan", "+359", "🇧🇬"),
        Country("Macarıstan", "+36", "🇭🇺"),
        Country("Slovakiya", "+421", "🇸🇰"),
        Country("Xorvatiya", "+385", "🇭🇷"),
        Country("Serbiya", "+381", "🇷🇸"),
        Country("İsrail", "+972", "🇮🇱"),
        Country("Ərəbistan", "+966", "🇸🇦"),
        Country("BƏƏ", "+971", "🇦🇪"),
        Country("Qatar", "+974", "🇶🇦"),
        Country("Küveyt", "+965", "🇰🇼"),
        Country("İran", "+98", "🇮🇷"),
        Country("İraq", "+964", "🇮🇶"),
        Country("Çin", "+86", "🇨🇳"),
        Country("Yaponiya", "+81", "🇯🇵"),
        Country("Koreya", "+82", "🇰🇷"),
        Country("Hindistan", "+91", "🇮🇳"),
        Country("Pakistan", "+92", "🇵🇰"),
        Country("Braziliya", "+55", "🇧🇷"),
        Country("Argentina", "+54", "🇦🇷"),
        Country("Meksika", "+52", "🇲🇽"),
        Country("Kanada", "+1", "🇨🇦"),
        Country("Avstraliya", "+61", "🇦🇺"),
        Country("Yeni Zelandiya", "+64", "🇳🇿"),
        Country("Cənubi Afrika", "+27", "🇿🇦"),
        Country("Nigeriya", "+234", "🇳🇬"),
        Country("Misir", "+20", "🇪🇬"),
        Country("Mərakeş", "+212", "🇲🇦"),
        Country("Tailand", "+66", "🇹🇭"),
        Country("Vyetnam", "+84", "🇻🇳"),
        Country("Malayziya", "+60", "🇲🇾"),
        Country("Sinqapur", "+65", "🇸🇬"),
        Country("İndoneziya", "+62", "🇮🇩"),
        Country("Filippin", "+63", "🇵🇭")
    )
}